main: br.com.vapoxmc.kitpvp.VapoxPvP
name: VapoxPvP
version: 0.0.0
description: Plugin de KitPvP do VapoxMC.
website: vapoxmc.com.br
authors: [SudanoJ, Carlos Henrique#0240]
commands:
  actionbar:
    description: Envie uma mensagem de actionbar.
    aliases: [ab]
  kit:
    description: Pegue seu kitpvp!
  resetkit:
    description: Remova o seu kit!
  spawn:
    description: Teleporte-se para o spawn!
  warp:
    description: Veja as warps do servidor