main: br.com.vapoxmc.kitpvp.VapoxPvP
name: VapoxPvP
version: 0.0.0
description: Plugin de KitPvP do VapoxMC.
website: vapoxmc.com.br
authors: [SudanoJ, Carlos Henrique#0240]
commands:
  kit:
    description: Pegue seu kitpvp!