main: br.com.vapoxmc.kitpvp.VapoxPvP
name: VapoxPvP
version: 0.0.0
description: Plugin de KitPvP do VapoxMC.
website: vapoxmc.com.br
authors: [SudanoJ, Carlos Henrique#0240]
commands:
  actionbar:
    description: Envie uma mensagem de actionbar.
    aliases: [ab]
  addmoney:
    description: Adicione dinheiro para alguem!
  admin:
    description: Acesse o modo admin!
  aplicar:
    description: Aplique-se para a staff!
  aviso:
    description: Faca um anuncio global.
  build:
    description: Ative e desative o modo build.
  chat:
    description: Altere as preferencias do chat.
  check:
    description: Veja o grupo de alguem.
  clicktest:
    description: Veja os cliques de alguem
  crash:
    description: Crashe um jogador.
  discord:
    description: Veja o convite do discord do servidor.
  fly:
    description: Ative o seu modo voar!
  gamemode:
    description: Altere seu modo de jogo.
    aliases: [gm]
  group:
    description: Altere o grupo de um jogador.
  head:
    description: Pegue a head de alguem.
  infocommand:
    description: Veja a informacao de um jogador!
  invsee:
    description: Veja o inventario de alguem!
  kit:
    description: Pegue seu kitpvp!
  lastlogin:
    description: Veja o ultimo acesso de alguem!
  money:
    description: Veja o seu saldo.
  online:
    description: Veja os jogadores online!
  ping:
    description: Veja a velocidade de conexao de alguem.
  rank:
    description: Veja a informacao dos ranks!
    aliases: [ranks]
  refresh:
    description: Reinicia o servidor.
  remmoney:
    description: Retire o dinheiro de alguém!
  report:
    description: Reporte um jogador!
  rtp:
    description: Teleporte-se para alguem.
  resetkit:
    description: Remova o seu kit!
  server:
    description: Veja as informacoes do servidor.
  setmoney:
    description: Defina o dinheiro de alguem!
  shop:
    description: Veja a loja do servidor.
  sorteio:
    description: Efetue um sorteio de moedas!
  spawn:
    description: Teleporte-se para o spawn!
  sc:
    description: fale algo no StaffChat
  status:
    description: Veja o seu proprio status.
    aliases: [stats]
  tag:
    description: Altere sua tag.
  tpall:
    description: Teleporte todo mundo ate voce.
  teleport:
    description: Teleporte para alguem.
    aliases: [tp]
  teleporthere:
    description: Teleporte alguem para voce.
    aliases: [tphere, tph]
  tell:
    description: Envie mensagens privadas!
  transferir:
    description: Envie moedas para um jogador!
  warp:
    description: Veja as warps do servidor
  youtuber:
    description: Veja os requitios para youtuber!
    aliases: [yt]