main: br.com.vapoxmc.kitpvp.VapoxPvP
name: VapoxPvP
version: 0.0.0
description: Plugin de KitPvP do VapoxMC.
website: vapoxmc.com.br
authors: [SudanoJ, Carlos Henrique#0240]
commands:
  actionbar:
    description: Envie uma mensagem de actionbar.
    aliases: [ab]
  aplicar:
    description: Aplique-se para a staff!
  aviso:
    description: Faca um anuncio global.
  crash:
    description: Crashe um jogador.
  discord:
    description: Veja o convite do discord do servidor.
  gamemode:
    description: Altere seu modo de jogo.
    aliases: [gm]
  head:
    description: Pegue a head de alguem.
  infocommand:
    description: Veja a informacao de um jogador!
  invsee:
    description: Veja o inventario de alguem!
  kit:
    description: Pegue seu kitpvp!
  online:
    description: Veja os jogadores online!
  ping:
    description: Veja a velocidade de conexao de alguem.
  rank:
    description: Veja a informacao dos ranks!
    aliases: [ranks]
  refresh:
    description: Reinicia o servidor.
  resetkit:
    description: Remova o seu kit!
  spawn:
    description: Teleporte-se para o spawn!
  sc:
    description: fale algo no StaffChat
  warp:
    description: Veja as warps do servidor